---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: docker://lpenz/omnilint:0.5.1
  rust:
    uses: lpenz/ghworkflow-rust/.github/workflows/rust.yml@v0.15.0
    with:
      coveralls: true
